spring:
  application:
    name: zuulservice
#服务发现配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry:  true
server:
  port: 5555
management:
  endpoints:
    web:
      exposure:
        include: '*'


